#### Deep Learning and Computer Vision

##### Training a small network

The aim of this exercise is to train a small network with dense layers for the classification of
handwritten digits. We are using the MNIST dataset, composed of 70,000 images: 60,000 for
training and 10,000 for testing. This is a classification problem with 10 categories

0/ Run the provided codes (Keras and Pytorch).

In [12]:
from keras.datasets import mnist     
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from keras.utils import np_utils
from keras.optimizers import gradient_descent_v2
import matplotlib.pyplot as plt

# Parameters
Sbatch=128
Nepochs=10
lr=1

# Load the dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Image Preprocessing
X_train = X_train.astype('float32')  
X_test = X_test.astype('float32')
X_train /= 255                     
X_test /= 255

# Labels
nb_classes = 10
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

# Create the Network
model = Sequential()
model.add(Flatten())
model.add(Dense(nb_classes))
model.add(Activation('softmax'))

# Loss and optimizer
model.compile(loss='categorical_crossentropy', optimizer=gradient_descent_v2.SGD(learning_rate=lr), metrics=['accuracy'])

# Training
model.fit(X_train, Y_train, batch_size=Sbatch, epochs=Nepochs, verbose=1)

# Test
score = model.evaluate(X_test, Y_test)
print('Test accuracy:', score[1])

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
Epoch 1/10
469/469 [==============================] - 1s 2ms/step - loss: 0.4282 - accuracy: 0.8795
Epoch 2/10
469/469 [==============================] - 1s 2ms/step - loss: 0.3121 - accuracy: 0.9118
Epoch 3/10
469/469 [======

KeyboardInterrupt: 

Questions about the Keras code (if you have time, you can do that again on the Pytorch code, after):

1/ What is the size of each image ?

In [7]:
print("The size of each image is:", X_train[0,:].shape)

The size of each image is: (28, 28)


2/ Display some labels before and after the function ‘to_categorical’.

In [22]:
for i in range(10):
    print("Label for image ", i, "is y = ", y_train[i])

Label for image  0 is y =  5
Label for image  1 is y =  0
Label for image  2 is y =  4
Label for image  3 is y =  1
Label for image  4 is y =  9
Label for image  5 is y =  2
Label for image  6 is y =  1
Label for image  7 is y =  3
Label for image  8 is y =  1
Label for image  9 is y =  4


3/ What is the aim of the ‘Flatten’ function ?

*Answer:* 

Flattens the input. Does not affect the batch size. if the input is size (1, 10, 64) after Flatten() it would be 640

4/ How many layers do we have in the current network ?

*Answer:*

Only 1, the Dense layer.

Sequential() groups a linear stack of layers into a tf.keras.Model,

Flatten() flattens the input, 

Dense() is just your regular densely-connected NN layer,

Activation('softmax') returns values in range (0,1).

5/ How many weights to be learned ?

*Answer:*

Dense is getting an input of the Flatten result. since the data is of size 28x28, the Flatten result would be 784.

6/ What are the loss function, the optimization algorithm and its parameter(s) ?


7/ What does ‘469/469’ mean in the output results ?


8/ Observe the prediction for the first test image and compare it with the actual label. Display the
first test image

9/ Display the learned weights of each neuron as an image.


10/ Insert FC layers (no convolution) and observe the results.


11/ Change the learning rate and observe the impact on the results. Do not touch the batch size or
the epoch number yet.

12/ Apply a 5-fold cross validation to tune the learning rate.


13/ Provide your best architecture and the number of learned weights.


14/ Try different batch sizes and explain the influence on accuracy and training time.